[log] print a dot every minute

diff --git a/botbrew b/botbrew
--- a/botbrew
+++ b/botbrew
@@ -364,9 +364,11 @@ botbrew_makefile() {
 				echo "clobber-${NAME}:"
 				echo "	cd ${G_ROOT}/${DIR}; ${G_ROOT}/botbrew recipe clobber"
 				echo "${G_ROOT}/${item}/${G_EXPORT}/.d:"
-				echo "	@echo -n 'Building ${NAME}...'"
-				echo "	@cd ${G_ROOT}/${DIR}; ${G_ROOT}/botbrew recipe build >${G_ROOT}/${G_LOG}/${NAME} 2>&1 || { mv ${G_ROOT}/${G_LOG}/${NAME} ${G_ROOT}/${G_LOG}/${NAME}.fail; echo 'KO'; cat ${G_ROOT}/${G_LOG}/${NAME}.fail; exit 1;}"
-				echo "	@echo 'ok'"
+				echo "	@echo -n 'Building ${NAME}'"
+				echo "	@rm -f ${G_ROOT}/${G_LOG}/${NAME} ${G_ROOT}/${G_LOG}/${NAME}.fail"
+				echo "	@(sleep 60; while [ ! -f '${G_ROOT}/${item}/${G_EXPORT}/.d' -a ! -f '${G_ROOT}/${G_LOG}/${NAME}.fail' ] && echo -n '.'; do sleep 60; done)&"
+				echo "	@cd ${G_ROOT}/${DIR}; (while [ ! -f ${G_ROOT}/${item}/${G_EXPORT}/.d ]; do sleep 60; echo -n '.'; done)& ${G_ROOT}/botbrew recipe build >${G_ROOT}/${G_LOG}/${NAME} 2>&1 || { jobs -p | xargs kill 2>/dev/null; mv ${G_ROOT}/${G_LOG}/${NAME} ${G_ROOT}/${G_LOG}/${NAME}.fail; echo '  KO'; cat ${G_ROOT}/${G_LOG}/${NAME}.fail; exit 1;}"
+				echo "	@echo '  ok'"
 				BUILDALL[${#BUILDALL[@]}]=${NAME}
 				PACKAGEALL[${#PACKAGEALL[@]}]="package-${NAME}"
 			fi
