[log] dump failed logs on error

diff --git a/botbrew b/botbrew
--- a/botbrew
+++ b/botbrew
@@ -365,7 +365,7 @@ botbrew_makefile() {
 				echo "	cd ${G_ROOT}/${DIR}; ${G_ROOT}/botbrew recipe clobber"
 				echo "${G_ROOT}/${item}/${G_EXPORT}/.d:"
 				echo "	@echo -n 'Building ${NAME}...'"
-				echo "	@cd ${G_ROOT}/${DIR}; ${G_ROOT}/botbrew recipe build >${G_ROOT}/${G_LOG}/${NAME} 2>&1 || { mv ${G_ROOT}/${G_LOG}/${NAME} ${G_ROOT}/${G_LOG}/${NAME}.fail; echo 'KO'; exit 1;}"
+				echo "	@cd ${G_ROOT}/${DIR}; ${G_ROOT}/botbrew recipe build >${G_ROOT}/${G_LOG}/${NAME} 2>&1 || { mv ${G_ROOT}/${G_LOG}/${NAME} ${G_ROOT}/${G_LOG}/${NAME}.fail; echo 'KO'; cat ${G_ROOT}/${G_LOG}/${NAME}.fail; exit 1;}"
 				echo "	@echo 'ok'"
 				BUILDALL[${#BUILDALL[@]}]=${NAME}
 				PACKAGEALL[${#PACKAGEALL[@]}]="package-${NAME}"
